version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: boxen
    versions:
    - 5.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: chalk
    versions:
    - 4.1.0
